/* =========================================================
   EcoPest - English ER model reference
   This SQL Server script is only used as a visual/reference model.
   The real application database is PostgreSQL and is generated by JPA/Hibernate.
   ========================================================= */

CREATE DATABASE EcoPestDB;
GO
USE EcoPestDB;
GO

CREATE TABLE roles (
    id_role BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(100) NOT NULL,
    active BIT NOT NULL
);
GO

CREATE TABLE business_entities (
    id_business_entity BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    type VARCHAR(20) NOT NULL,
    company_name VARCHAR(80) NOT NULL,
    active BIT NOT NULL,
    parent_business_entity_id BIGINT NULL,
    CONSTRAINT FK_business_entity_parent FOREIGN KEY (parent_business_entity_id)
        REFERENCES business_entities(id_business_entity)
);
GO

CREATE TABLE users (
    id_user BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    email VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    active BIT NOT NULL,
    id_role BIGINT NULL,
    id_business_entity BIGINT NULL,
    CONSTRAINT FK_user_role FOREIGN KEY (id_role) REFERENCES roles(id_role),
    CONSTRAINT FK_user_business_entity FOREIGN KEY (id_business_entity)
        REFERENCES business_entities(id_business_entity)
);
GO

CREATE TABLE pest_types (
    id_pest_type BIGINT IDENTITY(1,1) PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    description VARCHAR(200) NOT NULL
);
GO

CREATE TABLE inspections (
    id_inspection BIGINT IDENTITY(1,1) PRIMARY KEY,
    inspection_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    observations VARCHAR(300) NOT NULL,
    id_business_entity BIGINT NULL,
    id_user BIGINT NULL,
    CONSTRAINT FK_inspection_business_entity FOREIGN KEY (id_business_entity)
        REFERENCES business_entities(id_business_entity),
    CONSTRAINT FK_inspection_user FOREIGN KEY (id_user)
        REFERENCES users(id_user)
);
GO

CREATE TABLE incidents (
    id_incident BIGINT IDENTITY(1,1) PRIMARY KEY,
    incident_date DATE NOT NULL,
    description VARCHAR(300) NOT NULL,
    status VARCHAR(20) NOT NULL,
    id_inspection BIGINT NULL,
    id_pest_type BIGINT NULL,
    CONSTRAINT FK_incident_inspection FOREIGN KEY (id_inspection)
        REFERENCES inspections(id_inspection),
    CONSTRAINT FK_incident_pest_type FOREIGN KEY (id_pest_type)
        REFERENCES pest_types(id_pest_type)
);
GO

CREATE TABLE evidence (
    id_evidence BIGINT IDENTITY(1,1) PRIMARY KEY,
    file_url VARCHAR(500) NOT NULL,
    file_type VARCHAR(20) NOT NULL,
    upload_date DATETIME2 NOT NULL,
    id_incident BIGINT NOT NULL,
    CONSTRAINT FK_evidence_incident FOREIGN KEY (id_incident)
        REFERENCES incidents(id_incident)
);
GO

CREATE TABLE recommendations (
    id_recommendation BIGINT IDENTITY(1,1) PRIMARY KEY,
    description VARCHAR(1000) NOT NULL,
    origin VARCHAR(20) NOT NULL,
    generation_date DATETIME2 NOT NULL,
    status VARCHAR(20) NOT NULL,
    id_incident BIGINT NOT NULL,
    id_responsible_user BIGINT NULL,
    CONSTRAINT FK_recommendation_incident FOREIGN KEY (id_incident)
        REFERENCES incidents(id_incident),
    CONSTRAINT FK_recommendation_user FOREIGN KEY (id_responsible_user)
        REFERENCES users(id_user)
);
GO

CREATE TABLE weather_data (
    id_weather_data BIGINT IDENTITY(1,1) PRIMARY KEY,
    date DATE NOT NULL,
    temperature FLOAT NULL,
    humidity FLOAT NULL,
    source VARCHAR(50) NULL,
    id_business_entity BIGINT NOT NULL,
    CONSTRAINT FK_weather_business_entity FOREIGN KEY (id_business_entity)
        REFERENCES business_entities(id_business_entity),
    CONSTRAINT UQ_weather_entity_date UNIQUE (id_business_entity, date)
);
GO
