spring.application.name=ecopest

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/BDEcoPest
spring.datasource.username=postgres
spring.datasource.password=123

jwt.secret=252ab0301554214b191703cee7beda3514e91948148b850e2132098d5d8de8ce0d50b47d5de532fd6ab2a0ea40892f44fd73a3f6ae1b5ac4bddcb4e24557449e
